### ISSUE TITLE
could you public to mavencenter ~

### ISSUE THREAD

**Issue by wenfuli** [vitorhugods/AvatarView#15]
Nice avatar~~

**Comment by wenfuli** [comment]
nice avatar~~

**Comment by vitorhugods** [comment]
Hello @wenfuli.
I faced some issues doing that in the past and never tried to do so again, as it's possible to add the Bintray repository to the projects without a big hassle.

I'll give it a try again in the coming weeks.

**Comment by vitorhugods** [comment]
Hello @wenfuli 
I have the repositoy on jcenter at the moment.

Can you try the `1.1.1` version? It should be working fine :)

**Comment by vitorhugods** [comment]
I'll close this for now, as I managed to test the `1.1.1` version in multiple projects, in different CI/CD tools and the dependency was downloaded successfuly, even without needing to declare the bintray repository. JCenter is enough now.

If you face this issue again, please come here and I'll re-open the issue.

**Comment by wenfuli** [comment]
good job ， thx ！
