### ISSUE TITLE
Animation duration

### ISSUE THREAD

**Issue by nogovitsyndmitriy** [vitorhugods/AvatarView#17]
Hi! Thank you for you great custom view! 
I want to set duration time of animation. Or set number of animation scenes.
Thank you!

**Comment by vitorhugods** [comment]
Hello @nogovitsyndmitriy. What do you mean by animation scenes?

I'm thinking about adding custom animators.
Right now there are just two values that the animatos change in the view, these values regulate the rotation and the expansion of the small arches area when animating.
The animators also have their own duration, interpolation and repeating values.

I guess being able to plug different animation sequences that change these values can be a quick win that will allow for a lot of customisation when animating.
Would this help?

I don't think that allowing to properties other than the ones I mentioned before while animating is a good idea at this stage. The initial implementation of this library has far too many properties that only work based on this animation scheme (one big circle spliting into smaller arches). Maybe in a `2.0.0` version...

**Comment by nogovitsyndmitriy** [comment]
Hello! I mean, set a value to make the animation do one circle and
stop, or two circles. In general, regulation of this parameter. Most
likely I did not find it ...


пн, 28 дек. 2020 г. в 17:00, Vitor Hugo Schwaab <notifications@github.com>:

**Comment by vitorhugods** [comment]
@nogovitsyndmitriy In the release 1.2.0 you can create your own ValueAnimator and customise the animations to some degree.

If you want to use the default animation (or any other animation) and listen to animation events, just get the `baseAnimator` inside a `AvatarViewAnimator` and add listeners to it. 
You can also listen for the whole animation set by getting the fields inside a `AvatarViewAnimationOrchestrator`.
