### ISSUE TITLE
apply same behavior for any view like CardView

### ISSUE THREAD

**Issue by mohamadjavadx** [vitorhugods/AvatarView#19]

**Comment by vitorhugods** [comment]
What does this mean? What behaviour?
Any Screenshots?

**Comment by mohamadjavadx** [comment]
progress animation for cardView
somthing like this image (I know my drawing skill is weak)

![Screenshot 2021-01-03 231656](https://user-images.githubusercontent.com/57070063/103487373-19914880-4e1a-11eb-93dd-5120109a3438.png)

**Comment by vitorhugods** [comment]
@mohamadjavadx Even though this idea sounds interesting, I think it goes completely beyong the scope of this library.

I might give it a shot, making this progress animation border generic and applicable to other views. But it's not something I would commit to inside `AvatarView` library.

I'll close this for now.
