### ISSUE TITLE
Custom Animations

### ISSUE THREAD

**Issue by debajyotibasak** [vitorhugods/AvatarView#2]
Hey thanks for the awesome library. It saved me a lot of time in development. 
I just wanted to know if we can use custom animations instead of the normal rotation animation.

**Comment by vitorhugods** [comment]
Hello @debajyotibasak, what kind of animations, could you provide some images or gifs?
There isn't support for custom animations, yet.

If examples are provided, I am willing to study and implement this.

Pull requests are also welcome :D

**Comment by vitorhugods** [comment]
As no information or examples were given on how should the animations be customisable, I raised my own requirements.

As of version `1.2.0`, animations can be somewhat customisable. Check the sample app and/or `README.md` for examples.
