### ISSUE TITLE
How change image src?

### ISSUE THREAD

**Issue by mohsenmoqadam** [vitorhugods/AvatarView#20]
Dears can help me how I change image src programmatically?
Suppose `it` is `Uri` and this:
```
avatarView.setImageURI(it)
```
not work😞😞😞

**Comment by mohsenmoqadam** [comment]
it worked:
```
val parcelFileDescriptor = requireContext().contentResolver.openFileDescriptor(it, "r")
val fileDescriptor: FileDescriptor = parcelFileDescriptor!!.fileDescriptor
val image = BitmapFactory.decodeFileDescriptor(fileDescriptor)
parcelFileDescriptor!!.close()
avatarView.setImageBitmap(image)
```

**Comment by vitorhugods** [comment]
`AvatarView` does not override `setImageURI`, so it shouldn't be any different from a regular `ImageView`.

I can't say what was the `URI` you were using, or what was the issue that was happening to you in specific. But good to know you got it working.

I'll close the issue now :)
