### ISSUE TITLE
How to hide

### ISSUE THREAD

**Issue by lendljetleyba** [vitorhugods/AvatarView#6]
How do i hide the animation once it's done loading?

**Comment by vitorhugods** [comment]
In Kotlin:
```
view.isAnimating = false
```

**Comment by vitorhugods** [comment]
Please, check the example app for implementation details.

[This line](https://github.com/vitorhugods/AvatarView/blob/199605adcef8f049ada1447023f9c2537d715a64/app/src/main/java/xyz/schwaab/avvy/MainActivity.kt#L20), for example, is responsible for starting and stopping animation when clicking on the button.

```kotlin
        buttonToggleProgress.setOnClickListener {
            avatarView.isAnimating = !avatarView.isAnimating
		}
```
